### PR TITLE
Update the contributing.md and add link in README file

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #26 
I have updated the contributing.md file and added a link to our discord server in README file
Also added the following -
1. Difference between GIT and GITHUB
2. How to clone,fork repository
3. How to create a branch and then use git push to push to repo
4. Create a PR
5. Squash commits in a single issue into one
6. Updating the forked and local repo as the updations are made in the upstream
@learneradarsh @kaushik-rishi Have a look!

### CODE REVIEW

**Comment by learneradarsh** [comment]
1. There is one typo in the following line:
It might take a day or **tow** to review your pull request. Please have patience and be nice.
2. We need to mention the format of the branch any if we want to follow any:
Generally, for the feature branch, we use feature/<feature-name>
for tech task (small task like some tool installation like husky) we use techtask/<task-name>
Please rectify these things @khareyash05  and then let's merge this PR.


@kaushik-rishi  If we want to follow the approach of writing unit test cases with a feature we can write here only otherwise everything looks good.

**Comment by khareyash05** [comment]
I will look into that. Thanx @learneradarsh

**Comment by khareyash05** [comment]
Thank You @learneradarsh 
Could you pls add a GSSOC label and a level label to the same?

**Comment by khareyash05** [comment]
@learneradarsh @kaushik-rishi  Could you pls add a level label and a GSSOC label to the PR as well because adding a level label to the PR is only being counted
Thanx!

**Comment by kaushik-rishi** [comment]
> @learneradarsh @kaushik-rishi  Could you pls add a level label and a GSSOC label to the PR as well because adding a level label to the PR is only being counted
> Thanx!

Sorry for the delay. Thanks for reminding. Fixed it. @khareyash05

**Comment by khareyash05** [comment]
No problems @kaushik-rishi thanx

**Pull request merged**
