### PR TITLE
Fixed package.json scripts and Added sample makefile

### PR DESCRIPTION
**Pull request by Shubham-Kumar-2000**
Fixed issue#7

### CODE REVIEW

**Comment by kaushik-rishi** [comment]
I have verified the PR but refraining from merging it considering the fact that this may not come under `GSSOC`.
Tomorrow morning a new PR Template will be added just edit the description of the PR and it will be merged. @Shubham-Kumar-2000

**Comment by Shubham-Kumar-2000** [comment]
Added MakeFile in src/assets folder.

**Comment by kaushik-rishi** [comment]
@Shubham-Kumar-2000 Please edit the PR title saying `Add sample makefile`.

**Comment by Shubham-Kumar-2000** [comment]
Where will i get the PR Template for GSSoC?

**Comment by kaushik-rishi** [comment]
@Shubham-Kumar-2000 We are working on it. There's a meeting at 7PM and after that everything should be clear. 
I've tester your PR locally and everything works fine.
There are some improvements to be suggested.

**Comment by Shubham-Kumar-2000** [comment]
@kaushik-rishi  Ok sure.

**Comment by learneradarsh** [comment]
> Fixed issue#7

Hi @Shubham-Kumar-2000 ,

Thanks for working on the issue.
Could you please create a develop branch in your forked repo and raised PR from that to the main repo develop branch.
It will be more clean and easy to manage.

**Comment by Shubham-Kumar-2000** [comment]
Including both the PRs?

**Pull request merged**
