### PR TITLE
Solved a TODO for making folder for differnt CP Platforms

### PR DESCRIPTION
**Pull request by Yash1256**
This PR Solve the Issue #17 . Please have a look @kaushik-rishi .

### CODE REVIEW

**Comment by kaushik-rishi** [comment]
Can you please change the formatting of the code back to `single quotes` and `tab width: 4`.

**Comment by kaushik-rishi** [comment]
> This PR Solve the Issue #17 . Please have a look @kaushik-rishi .

Can you please change the formatting of the code back to `single quotes` and `tab width: 4`.

**Comment by kaushik-rishi** [comment]
Connect with us. We will resolve the conflict together. @Yash1256

**Comment by kaushik-rishi** [comment]
@Yash1256 The code base had updated a lot.
Please pull the changes from the master branch and resolve the conflict and update the PR accordingly

**Comment by Yash1256** [comment]
Ok @kaushik-rishi

**Pull request closed without merging**
