### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aditi1403**
I have made some grammatical edits to the README.md file. Kindly refer to PR #69.

### CODE REVIEW

**Comment by kaushik-rishi** [comment]
@aditi1403 Its actually Makefile in L#44
Kindly update the PR and it will be merged.

**Comment by aditi1403** [comment]
@kaushik-rishi Sir can you please guide me on what exactly I need to do...as I am a beginner.

**Comment by kaushik-rishi** [comment]
@aditi1403 Please join the discord server via the link in Readme. Secondly please don't call me a sir 🙄

**Comment by aditi1403** [comment]
@kaushik-rishi  It shows that the link is invalid or expired

**Comment by kaushik-rishi** [comment]
@aditi1403 https://discord.gg/wzjyjyACuR

**Pull request merged**
